<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>SEO Report - {{ $project->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            padding: 20px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .project-info {
            margin-bottom: 30px;
        }
        .log-entry {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .log-title {
            font-size: 16px;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
            background-color: #f3f4f6;
            padding: 8px;
        }
        .log-meta {
            font-size: 12px;
            color: #666;
            margin-bottom: 8px;
        }
        .log-content {
            font-size: 14px;
            margin-bottom: 15px;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #666;
            margin-top: 30px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>SEO Activity Report</h1>
        <h2>{{ $project->name }}</h2>
    </div>

    <div class="project-info">
        <p><strong>Customer:</strong> {{ $project->customer->name }}</p>
        <p><strong>Project Status:</strong> {{ $project->status_label }}</p>
        <p><strong>Report Generated:</strong> {{ $generatedAt->format('F j, Y, g:i a') }}</p>
    </div>

    <h3>SEO Activities Summary</h3>
    <p>Total Activities Included: {{ $seoLogs->count() }}</p>

    @foreach($seoLogs as $log)
        <div class="log-entry">
            <div class="log-title">{{ $log->title }}</div>
            <div class="log-meta">
                Type: {{ $log->type_label }} | Date: {{ $log->created_at->format('M d, Y') }} | By: {{ $log->user->name }}
            </div>
            <div class="log-content">
                {!! nl2br(e($log->content)) !!}
            </div>

            @if($log->media->count() > 0)
                <div class="log-attachments">
                    <p><strong>Attachments:</strong> {{ $log->media->count() }} file(s)</p>
                </div>
            @endif
        </div>

        @if(!$loop->last)
            <div style="border-bottom: 1px solid #ddd; margin: 20px 0;"></div>
        @endif
    @endforeach

    <div class="footer">
        <p>Generated by {{ config('app.name') }} | {{ $generatedAt->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html> 