<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>SEO Report - {{ $project->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            padding: 20px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #333;
        }
        .logos {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .logo {
            max-width: 150px;
            max-height: 80px;
        }
        .overview {
            margin-bottom: 30px;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
        .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
            padding-bottom: 5px;
            border-bottom: 1px solid #ddd;
        }
        .section-content {
            margin-bottom: 15px;
        }
        .log-entry {
            margin-bottom: 25px;
            page-break-inside: avoid;
        }
        .log-title {
            font-size: 16px;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
            background-color: #f3f4f6;
            padding: 8px;
        }
        .log-meta {
            font-size: 12px;
            color: #666;
            margin-bottom: 8px;
        }
        .log-content {
            font-size: 14px;
            margin-bottom: 15px;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            color: #666;
            margin-top: 30px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logos">
            <img src="{{ $project->logo_url }}" alt="Project Logo" class="logo">
            <img src="{{ $project->customer->logo_url }}" alt="Customer Logo" class="logo">
        </div>
        <h1>SEO Activity Report</h1>
        <h2>{{ $project->name }}</h2>
    </div>

    <div class="overview">
        <h3>Overview</h3>
        {!! nl2br(e($overview)) !!}
    </div>

    @foreach($sections as $section)
        <div class="section">
            <div class="section-title">{{ $section['title'] }}</div>
            <div class="section-content">
                {!! nl2br(e($section['content'])) !!}
            </div>
        </div>
    @endforeach

    <div class="page-break"></div>

    <h3>SEO Activities Log</h3>
    @foreach($seoLogs as $log)
        <div class="log-entry">
            <div class="log-title">{{ $log->title }}</div>
            <div class="log-meta">
                Type: {{ $log->type_label }} | Date: {{ $log->created_at->format('M d, Y') }} | By: {{ $log->user->name }}
            </div>
            <div class="log-content">
                {!! nl2br(e($log->content)) !!}
            </div>

            @if($log->media->count() > 0)
                <div class="log-attachments">
                    <p><strong>Attachments:</strong> {{ $log->media->count() }} file(s)</p>
                </div>
            @endif
        </div>

        @if(!$loop->last)
            <hr>
        @endif
    @endforeach

    <div class="footer">
        <p>Generated by {{ config('app.name') }} | {{ $generatedAt->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html> 