<?php /* Preview template for SEO report */ ?>

<div class="p-6">
    <div class="text-center mb-8">
        <h1 class="text-2xl font-bold mb-2">SEO Activity Report</h1>
        <h2 class="text-xl">{{ $project->name }}</h2>
    </div>

    <div class="mb-8">
        <div class="grid grid-cols-2 gap-4">
            <div>
                <p><strong>Customer:</strong> {{ $project->customer->name }}</p>
                <p><strong>Project Status:</strong> {{ $project->status_label }}</p>
            </div>
            <div>
                <p><strong>Report Generated:</strong> {{ $generatedAt->format('F j, Y, g:i a') }}</p>
                <p><strong>Total Activities:</strong> {{ $seoLogs->count() }}</p>
            </div>
        </div>
    </div>

    <div class="mb-8">
        <h3 class="text-lg font-semibold mb-4">SEO Activities Summary</h3>
        
        @foreach($seoLogs as $log)
            <div class="mb-6 p-4 bg-gray-50 rounded-lg">
                <div class="font-semibold text-lg mb-2">{{ $log->title }}</div>
                <div class="text-sm text-gray-600 mb-2">
                    Type: {{ $log->type_label }} | Date: {{ $log->created_at->format('M d, Y') }} | By: {{ $log->user->name }}
                </div>
                <div class="prose max-w-none">
                    {!! nl2br(e($log->content)) !!}
                </div>

                @if($log->media->count() > 0)
                    <div class="mt-2 text-sm text-gray-600">
                        <strong>Attachments:</strong> {{ $log->media->count() }} file(s)
                    </div>
                @endif
            </div>

            @if(!$loop->last)
                <hr class="my-4">
            @endif
        @endforeach
    </div>

    <div class="text-center text-sm text-gray-600 mt-8">
        <p>Generated by {{ config('app.name') }} | {{ $generatedAt->format('Y-m-d H:i:s') }}</p>
    </div>
</div> 